# nixpacks.toml
# A more robust list of system packages for Puppeteer to run on Railway's Ubuntu environment.

[phases.setup]
aptPkgs = [
    "libnss3",
    "libnspr4",
    "libdbus-1-3",
    "libatk1.0-0",
    "libatk-bridge2.0-0",
    "libcups2",
    "libdrm2",
    "libgtk-3-0",
    "libgbm1",
    "libasound2",
    "libatspi2.0-0",
    "libx11-6",
    "libx11-xcb1",
    "libxcb1",
    "libxcomposite1",
    "libxcursor1",
    "libxdamage1",
    "libxext6",
    "libxfixes3",
    "libxi6",
    "libxrandr2",
    "libxrender1",
    "libxss1",
    "libxtst6"
]
