# nixpacks.toml

# This tells Railway to install system packages using the apt package manager
[phases.setup]
aptPkgs = [
    "libnss3",
    "libatk1.0-0",
    "libatk-bridge2.0-0",
    "libcups2",
    "libgtk-3-0",
    "libgbm-dev",
    "libasound2",
    "libxshmfence1"
]
